Entity/Term.php
<?php

namespace PSS\Bundle\BlogBundle\Entity;


// Symfony/Doctrine internal
use Doctrine\ORM\Mapping as ORM;


// Specific


// Domain objects


// Entities
use PSS\Bundle\BlogBundle\Entity\TermTaxonomy;




/**
 * @ORM\Table(name="wp_terms")
 * @ORM\Entity(repositoryClass="PSS\Bundle\BlogBundle\Repository\TermRepository")
 */
class Term implements \PSS\Bundle\BlogBundle\TagCloud\TagInterface
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="term_id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=200, nullable=false)
     */
    private $name;

    /**
     * @var string $slug
     *
     * @ORM\Column(name="slug", type="string", length=200, nullable=false)
     */
    private $slug;

    /**
     * @var integer $group
     *
     * @ORM\Column(name="term_group", type="bigint", nullable=false)
     */
    private $group;

    /**
     * @var Collection $termTaxonomies
     *
     * @ORM\OneToMany(targetEntity="TermTaxonomy", mappedBy="term")
     * @ORM\JoinColumn(name="term_id", referencedColumnName="term_id")
     */
    private $termTaxonomies;


    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }


    /**
     * @return integer
     */
    public function getFrequency()
    {
        return $this->getPostCount();
    }


    /**
     * @return integer
     */
    public function getPostCount()
    {
        $termTaxonomy = $this->getPostTagTaxonomy();

        return is_null($termTaxonomy) ? 0 : $termTaxonomy->getPostCount();
    }


    /**
     * @return PSS\Bundle\BlogBundle\Entity\TermTaxonomy
     */
    private function getPostTagTaxonomy()
    {
        if (!is_null($this->termTaxonomies)) {
            foreach ($this->termTaxonomies as $termTaxonomy) {
                if (TermTaxonomy::POST_TAG  == $termTaxonomy->getTaxonomy()) {
                    return $termTaxonomy;
                }
            }
        }

        return null;
    }


    public function __construct()
    {
        $this->termTaxonomies = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Get id
     *
     * @return bigint 
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }


    /**
     * Set slug
     *
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }


    /**
     * Set group
     *
     * @param bigint $group
     */
    public function setGroup($group)
    {
        $this->group = $group;
    }


    /**
     * Get group
     *
     * @return bigint 
     */
    public function getGroup()
    {
        return $this->group;
    }


    /**
     * Add termTaxonomies
     *
     * @param PSS\Bundle\BlogBundle\Entity\TermTaxonomy $termTaxonomies
     */
    public function addTermTaxonomy(\PSS\Bundle\BlogBundle\Entity\TermTaxonomy $termTaxonomies)
    {
        $this->termTaxonomies[] = $termTaxonomies;
    }


    /**
     * Get termTaxonomies
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getTermTaxonomies()
    {
        return $this->termTaxonomies;
    }
}

Controller/BlogController.php
<?php

namespace PSS\Bundle\BlogBundle\Controller;


# Symfony/Doctrine internal
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;


# Specific


# Domain objects


# Entities
use PSS\Bundle\BlogBundle\Entity\Post;
use PSS\Bundle\BlogBundle\Entity\Term;



/**
 * Base Controller
 *
 * Basic views available here, to override you can 
 * use the PostManager service. The idea of this controller
 * is that you can extend as a Base, and alter the returned array()
 * that each method returns using parent::methodName();
 *
 * Cookbook in PSSBlogBundle/Resources/doc/recipe-extending-blog-controller.md
 * 
 * @Route("/blog")
 */
class BlogController extends Controller
{
    /**
     * Generate a comment form and process
     */
    protected function comment(Request $request, Post $post)
    {
#        try {
#            $cmtMgr = $this->get('pss.blogbundle.manager.comment');
#            $entity = $cmtMgr->entityFactory($request); // Setting the "always required" stuff
    }

    /**
     * @Route("/{year}/{month}/{slug}", name="blog_show")
     * @Template()
     */
    public function showAction(Post $post, Request $request)
    {
        return array(
            'post' => $post->onlyIfPublished(),
            'comment_form' => $this->comment($request,$post)
        );
    }

    /**
     * @Route("/", name="blog_index")
     * @Template()
     */
    public function indexAction()
    {
        $pm = $this->getPostManager();
        $paginator = $this->createPaginator($pm->getRepository()->getPublishedPostsQuery());

        return array(
            'paginator' => $paginator
        );
    }

    /**
     * @Route("/tag/{slug}", name="blog_posts_by_tag")
     * @Template()
     */
    public function postsByTagAction(Term $term)
    {
        $pm = $this->getPostManager();
        $repository = $pm->getRepository();
        $query = $repository
                        ->getPublishedByTerm($term);

        $paginator = $this->createPaginator($query->getQuery());

        if ($paginator->getTotalItemCount() == 0) {
            throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException('Page Not Found');
        }

        return array(
            'paginator' => $paginator,
            'term'      => $term
        );
    }

    public function recentPostsAction($max)
    {
        $entityManager = $this->get('doctrine.orm.entity_manager');

        $posts = $entityManager
            ->getRepository('PSS\Bundle\BlogBundle\Entity\Post')
            ->findPublishedPosts($max);

        return $this->render('PSSBlogBundle:Blog:recentPosts.html.twig', array('posts' => $posts));
    }

    public function tagCloudAction()
    {
        $entityManager = $this->get('doctrine.orm.entity_manager');

        $tags = $entityManager
            ->getRepository('PSS\Bundle\BlogBundle\Entity\Term')
            ->findAllTags();

        $tagCloud = new \PSS\Bundle\BlogBundle\TagCloud\TagCloud($tags, array('size1', 'size2', 'size3', 'size4', 'size5', 'size6', 'size7', 'size8'));

        return $this->render('PSSBlogBundle:Blog:tagCloud.html.twig', array('tagCloud' => $tagCloud));
    }

    /**
     * Access to Post Manager service
     * 
     * @return \PSS\Bundle\BlogBundle\Manager\PostManager
     */
    protected function getPostManager()
    {
        return $this->get('pss.blog.manager.post');
    }

    /**
     * Create a paginator from a Query
     *
     * @param \Doctrine\ORM\Query $query
     *
     * @return \Knp\Component\Pager\Pagination\PaginationInterface
     */
    protected function createPaginator(\Doctrine\ORM\Query $query)
    {
        $paginator = $this->get('knp_paginator');
        $request = $this->get('request');
        $page = $request->query->get('page', 1);

        return $paginator->paginate($query, $page, 3);
    }
}

Resources/views/Blog/feed.rss.twig
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
    xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
>

<channel>
    <title>{{ options.blogname }}</title>
    <atom:link href="{{ url('blog_feed') }}" rel="self" type="application/rss+xml" />
    <link>{{ options.siteurl }}</link>
    <description></description>
    <lastBuildDate>Wed, 03 Nov 2010 12:06:15 +0000</lastBuildDate>
    <language>{{ options.rss_language }}</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    {% for post in posts %}
        <item>
            <title>{{ post.title }}</title>
            <link>{{ url('blog_show', {'slug' : post.slug}) }}</link>
            <pubDate>{{ post.publishedAt | date('r') }}</pubDate>
            <dc:creator>{{ post.author.displayName }}</dc:creator>
            <description><![CDATA[{{ post.excerpt | raw }}]]></description>
            <content:encoded><![CDATA[{{ post.content | raw }}]]></content:encoded>
        </item>
    {% endfor %}
</channel>
</rss>

Resources/views/Blog/index.html.twig
{% extends 'PSSBlogBundle::layout.html.twig' %}

{% block content %}
    {% include 'PSSBlogBundle:Blog:postsList.html.twig' with {'paginator': paginator} %}
{% endblock %}

{% block sidebar %}
    {% render 'PSSBlogBundle:Blog:tagCloud' %}
{% endblock %}

Resources/views/Blog/postsByTag.html.twig
{% extends 'PSSBlogBundle::layout.html.twig' %}

{% block content %}
    {% include 'PSSBlogBundle:Blog:postsList.html.twig' with {'paginator': paginator} %}
{% endblock %}

{% block sidebar %}
    {% render 'PSSBlogBundle:Blog:tagCloud' %}
{% endblock %}

Resources/views/Blog/postsList.html.twig
{% for post in paginator %}
    <h2><a href="{{ path('blog_show', {'slug': post.slug, 'year': post.year, 'month': post.month }) }}" rel="bookmark" title="{{ post.title }}">{{ post.title }}</a></h2>

    {% if post.excerpt %}
        {{ post.excerpt | autop | raw }}
    {% else %}
        {% set moreLink = '<a class="more" href="' ~ path('blog_show', {'slug': post.slug, 'year': post.year, 'month': post.month, 'year': post.year, 'month': post.month }) ~ '" title="' ~  post.title ~ '">' ~ '&raquo; Read more' | trans ~ '</a>' %}
        {{ post.content | autop | more(moreLink) | raw }}
    {% endif %}
    <div class="post-meta">
        {% trans with { '%date%': post.publishedAt | date('d M Y'), '%author%': post.author.displayName } %}Posted on %date% by %author%{% endtrans %}
    </div>
{% endfor %}
<div class="paginator">
    {{ paginator.render() | raw }}
</div>

Resources/views/Blog/recentPosts.html.twig
<h3>Recent posts</h3>
<ul>
    {% for post in posts %}
        <li><a href="{{ path('blog_show', {'slug': post.slug, 'year': post.year, 'month': post.month }) }}" rel="bookmark" title="{{ post.title }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

Resources/views/Blog/show.html.twig
{% extends 'PSSBlogBundle::layout.html.twig' %}

{% block content %}
    <h1>{{ post.title }}</h1>

    {{ post.content | autop | raw }}
{% endblock %}

{% block sidebar %}
    {% render 'PSSBlogBundle:Blog:recentPosts' with {'max': 5} %}
{% endblock %}

Resources/views/Blog/tagCloud.html.twig
<ul class="tag-cloud">
    {% for tag in tagCloud.tags %}
        {% set count=tag.frequency %}
        <li class="{{ tag.weight }}"><a href="{{ path('blog_posts_by_tag', { 'slug': tag.slug }) }}"  title="{% transchoice count with { '%tag%': tag.name } %}{0} No posts taggged with %tag%|{1} One post tagged with %tag%|]1,+Inf] %count% posts tagged with %tag%{% endtranschoice %}">{{ tag.name|capitalize }}</a></li>
    {% endfor %}
</ul>